Add design guide for graphql naming conventions
island-is/handbook pull request #31
Opened 2020-10-14 10:23 UTC by darrikonn

2020-10-14 11:51 UTC, eirikurn commented
Great!

I prefer namespace prefixing. It is closer to this [proposal](https://medium.com/@oleg.ilyenko/graphql-namespaces-proposal-2a097ce81d2a), which is being [considered](https://github.com/graphql/graphql-wg/blob/master/notes/2020-06-11.md#graphql-namespaces-20m-courtney) (tldr, they are weighing implementation complexity vs letting the community handle namespacing on their own).

Type:

1. search_Article
2. Search_Article
3. Article_Search

Query:

1. search_article
2. Search_article
3. article_Search

Mutation:

1. search_indexArticle
2. Search_indexArticle
3. indexArticle_search

My preference is #1 because:

1. Namespaces are usually prefixed in environments that don't support them natively.
2. All of our (nest/nx/npm) modules are lower case.

2020-10-14 11:55 UTC, eirikurn commented
We'll probably add more sections to this as time goes by, but I'd like to document one important best practice for future compatibility, to never resolve arrays directly. Always wrap arrays in some kind of payload object.

2020-10-14 12:01 UTC, darrikonn commented
Yeah agree with the prefix after seeing the article.
But what about `underscore` vs. `slash`?

Can you elaborate on:

	to never resolve arrays directly. Always wrap arrays in some kind of payload object.

2020-10-14 12:22 UTC, eirikurn commented
I'd prefer a slash, but it's not a supported symbol in identifiers, which is why they're proposing it for the standard.

The only non-alphanumerical symbol is "_".

Regarding arrays, it's mainly about pagination. It's classic to start with arrays and return all items and then having no way to add cursor-based pagination with backwards compatibility.

Worth having a naming convention for pagination?

2020-10-14 12:27 UTC, eirikurn commented
I guess this guide should be implementation independent, but practically, in NestJS, I think this involves always passing explicit names to type and resolver decorators:

```
@ObjectType('search_Article')
class Article {}

@Resolver()
class ArticleResolver {
  @Query(() => Article, { name: 'search_article' }
  getArticle() {}

  @Mutation({ name: 'search_indexArticle' })
  indexArticle() {}
}
```

2020-10-14 12:29 UTC, darrikonn commented
Yeah I see!
Not keen on `Worth having a naming convention for pagination?`.

My vote would be `relay-style pagination`.
```graphql
query {
  dog {
    id
    owners {
      count
	  edges {
        cursor
        node {
          id
        }
	  }
      pageInfo {
	    hasNextPage
	    endCursor
	  }
    }
  }
}
```

2020-10-14 12:30 UTC, darrikonn commented
```We should consider creating an eslint rule to enforce this naming convention, as it is easy to forget during implementation and review.```

Yeah, my original thought was to prefix it at runtime.

2020-10-14 12:48 UTC, eirikurn commented
That would be ideal, but it'd be an exercise in NestJS. There is a `transformSchema` hook, but that happens after merging all the domains/resolvers (which either fails or overrides stuff on conflict).

We'd have to implement the code-first schema generation logic from scratch, or create a GraphQLModule in each domain and somehow merge them manually. :/

2020-10-14 13:59 UTC, darrikonn commented
What's your thought on `relay pagination style`?

2020-10-14 21:31 UTC, eirikurn commented
I've never gone for it before because the pattern feels a bit bloated, with two types per connection (Connection type and Edge type), and extra wrapping/unwrapping needed both on server and client.

I would personally base our convention on the Connection pattern but simplify, skipping the Edge type, unless:

1. We want to support Relay at some point.
2. We want to follow "best practices" according to graphql.org.
3. We think there's a use case for getting per-edge cursor.
4. We feel confident in creating awesome pagination utilities on server and client (though this is useful either way).

For #1 and #2, we might also want to discuss the `node` pattern.

2020-10-14 22:00 UTC, eirikurn commented
How about simplifying namespacing rules and skip the namespace symbol. Just prefix the namespace and follow casing rules? E.g.

Type: SearchArticle instead of search_Article
Field: searchArticle instead of search_article

This would make queries, result objects and generated types cleaner, following our global casing rules (no screaming eslint rules).

The cons would be:

* Potentially silly names (`ApplicationsApplication`?).
* Not obvious where namespace ends and field starts. E.g. mutations would feel prefixed by a noun (`applicationsCreateApplication` vs `applications_createApplication`).
* Potential conflict if one namespace is a prefix for another (`Search-IndexResult vs SearchIndex-Result`). Easy to avoid.

2020-10-15 09:11 UTC, darrikonn commented
This answer sums it quite well why there's a per-edge cursor:
```
We fetch cursors on every edge so that if you have a component that asks for first:10 and have it cached and later another component asks for first:5, we can generated the correct pageInfo based on the cursors we have fetched from first:10 for first:5 without doing a server round trip.
Another case is, if some of the edges are deleted through mutations, we still have the cursors from the other edges to fetch for additional edges.
```


Regarding `How about simplifying namespacing rules and skip the namespace symbol`:
I think it makes sense for queries, like `ApplicationsApplication` is actually super descriptive!

But IMO the mutation names would have to have a pretty specific rule. Like `createApplicationsApplication` is really descriptive and I'd prefer that over `applicationsCreateApplication`. So the general rule would be:
`Name your mutations verb first. Then the module name, following the object, or “noun,” if applicable`

2020-10-15 17:25 UTC, eirikurn commented
IMO those feel like very specific edge cases (pun intended), which is tricky to get right unless we're using Relay. Meanwhile spending more bytes and compute cycles for the general cases.

I think your mutation rule is fair. Again, custom eslint to the rescue:

```
"@island-is/namespaced-graphql-schema": [
  "error",
  {
    "namespaces": [
      "applications",
      "cms",
      "search"
    ]
  }
]
```

It can visit graphql resolvers, types and enums based on the nestjs directives, and verify that they have one of the namespace prefixes (ignores the verb for mutations).

2020-10-16 10:45 UTC, darrikonn commented
Ready for re-review.
Please let me know if something isn't in line with our discussion above.

2020-10-16 17:41 UTC, eirikurn requested changes

2020-10-16 17:41 UTC, eirikurn commented on docs/api-design-guide/graphql-naming-conventions.md
> +The mutation structure should follow the Relay's connection pattern (simplifying the
Referring to mutations instead of pagination.

Also I’d say lists work quite different from single fields.

2020-10-16 17:41 UTC, eirikurn commented on docs/api-design-guide/graphql-naming-conventions.md
> +      edges {
Should be `items` IMO if we’re skipping the edge model.

I feel a bit bad deciding this part without more discussion. Maybe it’s fine to start here and reevaluate later.

2020-10-19 10:22 UTC, darrikonn commented
Fixed based on Conversation, and due to parental leave (Congrats!) I'm gonna merge this in so it won't become stale

2020-10-19 10:22 UTC, merged