Document branching/release strategy
island-is/handbook pull request #8
Opened 2020-06-02 01:00 UTC by eirikurn

Documenting #5 in handbook.

2020-07-22 13:41 UTC, pshomov reviewed
A lot of good changes 👍

2020-08-18 14:12 UTC, AndriMar requested changes

2020-09-28 13:46 UTC, pshomov commented
@eirikurn @AndriMar can we close this so it is on master and people can access it easily? I can add some of the comments to the content if you guys don't have the time.

2020-11-25 11:10 UTC, jeremybarbet commented
Closing in favor of https://github.com/island-is/island.is/pull/2019

2020-11-25 11:10 UTC, closed without merging